#!/usr/bin/env python

import argparse

from src.commands import new, start, done
from src.config import get_workstream_name

parser = argparse.ArgumentParser(description='mobn git handoff tool')
parser.add_argument('command', help='the command (eg say, new)')
parser.add_argument('arguments', nargs='*',
                    help='arguments to the command (eg huhuhu)')
args = parser.parse_args()



def runAll(effects):
    for effect in effects:
        effect.run()


if args.command == "new":
    runAll(new(get_workstream_name()))
elif args.command == "continue":
    runAll(start(get_workstream_name()))
elif args.command == "done":
    runAll(done(args.arguments[0]))
