#!/usr/bin/env python
import argparse
from subprocess import Popen, PIPE, STDOUT

def branch():
    process = Popen(['git branch'], shell=True, stdin=PIPE, stdout=PIPE, stderr=PIPE, )
    output, _ = process.communicate()
    print(str(output.decode("utf-8")))

def create_branch(name):
    process = Popen(['git checkout -b {}'.format(name)], shell=True, stdin=PIPE, stdout=PIPE, stderr=PIPE, )
    output, _ = process.communicate()
    print(str(output.decode("utf-8")))

def say(phrase):
    process = Popen(['say {}'.format(phrase)], shell=True, stdin=PIPE, stdout=PIPE, stderr=PIPE, )
    output, _ = process.communicate()
    print(str(output.decode("utf-8")))

parser = argparse.ArgumentParser(description='mobn git handoff tool')
parser.add_argument('command',)
parser.add_argument('argumentss', metavar='say',
                    help='')
args = parser.parse_args()

if args.command == "say":
    say("huhuhu")

if __name__ == '__main__':
    pass
    # say("huhuhuhuhuhuhuhuh")
