#!/usr/bin/env python
import argparse
from subprocess import Popen, PIPE, STDOUT

def branch():
    process = Popen(['git branch'], shell=True, stdin=PIPE, stdout=PIPE, stderr=PIPE, )
    output, _ = process.communicate()
    print(str(output.decode("utf-8")))

def create_branch(name):
    process = Popen(['git checkout -b {}'.format(name)], shell=True, stdin=PIPE, stdout=PIPE, stderr=PIPE, )
    output, _ = process.communicate()
    print(str(output.decode("utf-8")))

def say(phrase):
    process = Popen(['say {}'.format(phrase)], shell=True, stdin=PIPE, stdout=PIPE, stderr=PIPE, )
    output, _ = process.communicate()
    print(str(output.decode("utf-8")))

parser = argparse.ArgumentParser(description='mobn git handoff tool')
parser.add_argument('command', help='the command (eg say)')
parser.add_argument('arguments', nargs='+',
                    help='arguments to the command (eg huhuhu)')
args = parser.parse_args()

if args.command == "say":
    say(' '.join(args.arguments))

if __name__ == '__main__':
    pass
    # say("huhuhuhuhuhuhuhuh")
